### ISSUE TITLE
In Rails 4 Load Error

### ISSUE THREAD

**Issue by ambey99** [joshk/completeness-fu#12]
bundle install works fine but when I am restarting rails server getting following error:

 * actionmailer (4.2.5.1)
  * actionpack (4.2.5.1)
  * actionview (4.2.5.1)
  * activeadmin (1.0.0)
  * activejob (4.2.5.1)
  * activemodel (4.2.5.1)
  * activerecord (4.2.5.1)
  * activesupport (4.2.5.1)
  * addressable (2.5.1)
  * airbrussh (1.2.0)
  * arbre (1.1.1)
  * arel (6.0.4)
  * autoprefixer-rails (6.7.7.2)
  * bcrypt (3.1.11)
  * binding_of_caller (0.7.2)
  * bootstrap-sass (3.3.7)
  * bourbon (4.3.4)
  * builder (3.2.3)
  * bundler (1.14.6)
  * byebug (9.0.6)
  * capistrano (3.8.1)
  * capistrano-bundler (1.2.0)
  * capistrano-rails (1.2.3)
  * chronic (0.10.2)
  * climate_control (0.1.0)
  * cocaine (0.5.8)
  * coffee-rails (4.1.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.12.2)
  * completeness-fu (0.6.0)
  * concurrent-ruby (1.0.5)
  * cookiejar (0.3.3)
  * daemons (1.2.4)
  * debug_inspector (0.0.2)
  * devise (4.2.1)
  * dropbox-sdk (1.6.5)
  * em-http-request (1.1.5)
  * em-socksify (0.3.1)
  * erubis (2.7.0)
  * eventmachine (1.0.9.1)
  * execjs (2.7.0)
  * faraday (0.11.0)
  * faye (1.1.2)
  * faye-rails (2.0.3)
  * faye-websocket (0.10.7)
  * figaro (1.1.1)
  * font-awesome-sass (4.5.0)
  * foreman (0.84.0)
  * formtastic (3.1.5)
  * formtastic_i18n (0.6.0)
  * geocoder (1.4.3)
  * globalid (0.4.0)
  * haml (4.0.7)
  * haml-rails (1.0.0)
  * has_scope (0.7.0)
  * hashie (3.5.5)
  * html2haml (2.1.0)
  * http_parser.rb (0.6.0)
  * httparty (0.14.0)
  * hubspot-ruby (0.2.1)
  * i18n (0.8.1)
  * inherited_resources (1.7.1)
  * jbuilder (2.6.3)
  * jquery-rails (4.3.1)
  * jquery-raty-rails (0.0.2 d36753c)
  * jquery-ui-rails (6.0.1)
  * json (1.8.6)
  * jwt (1.5.6)
  * kaminari (1.0.1)
  * kaminari-actionview (1.0.1)
  * kaminari-activerecord (1.0.1)
  * kaminari-core (1.0.1)
  * loofah (2.0.3)
  * mail (2.6.4)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mimemagic (0.3.0)
  * mini_portile2 (2.1.0)
  * minitest (5.10.1)
  * multi_json (1.12.1)
  * multi_xml (0.6.0)
  * multipart-post (2.0.0)
  * mysql2 (0.4.5)
  * net-scp (1.2.1)
  * net-ssh (4.1.0)
  * nokogiri (1.7.1)
  * oauth (0.5.1)
  * oauth2 (1.3.1)
  * omniauth (1.6.1)
  * omniauth-facebook (4.0.0)
  * omniauth-google-oauth2 (0.4.1)
  * omniauth-linkedin (0.2.0)
  * omniauth-oauth (1.1.0)
  * omniauth-oauth2 (1.4.0)
  * orm_adapter (0.5.0)
  * paperclip (4.3.7)
  * paperclip-dropbox (1.3.2)
  * pg (0.20.0)
  * polyamorous (1.3.1)
  * private_pub (1.0.3)
  * public_activity (1.5.0)
  * public_suffix (2.0.5)
  * rack (1.6.5)
  * rack-test (0.6.3)
  * rails (4.2.5.1)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.8)
  * rails-html-sanitizer (1.0.3)
  * rails_12factor (0.0.3)
  * rails_serve_static_assets (0.0.5)
  * rails_stdout_logging (0.0.5)
  * railties (4.2.5.1)
  * rake (12.0.0)
  * ransack (1.8.2)
  * rdoc (4.3.0)
  * redis (3.3.3)
  * responders (2.3.0)
  * ruby_parser (3.9.0)
  * sass (3.4.23)
  * sass-rails (5.0.6)
  * sdoc (0.4.2)
  * sexp_processor (4.9.0)
  * simple_form (3.4.0)
  * spring (2.0.1)
  * sprockets (3.7.1)
  * sprockets-rails (3.2.0)
  * sshkit (1.13.1)
  * thin (1.7.0)
  * thor (0.19.4)
  * thread_safe (0.3.6)
  * tilt (2.0.7)
  * toastr-rails (1.0.3)
  * turbolinks (5.0.1)
  * turbolinks-source (5.0.0)
  * tzinfo (1.2.3)
  * uglifier (3.2.0)
  * warden (1.2.7)
  * web-console (2.3.0)
  * websocket-driver (0.6.5)
  * websocket-extensions (0.1.2)
  * whenever (0.9.7)
  * wicked (1.3.1)

cannot load such file -- active_support/core_ext/class/inheritable_attributes (LoadError)
	from /home/yuva/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/yuva/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'

**Comment by JonnalagaddaDevi** [comment]
I am getting the same error. Did you find any solution for this?
